package com.insthub.cat.android.wxapi;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;

import com.common.android.fui.rxanroid.RxBusManager;
import com.common.android.futils.ToastUtil;
import com.common.rxpay.sdk.PaymentStatus;
import com.common.rxpay.sdk.wechatpay.WXPayWay;
import com.insthub.cat.android.R;
import com.insthub.cat.android.event.ThirdOauthEvent;
import com.tencent.mm.sdk.modelbase.BaseReq;
import com.tencent.mm.sdk.modelbase.BaseResp;
import com.tencent.mm.sdk.modelmsg.SendAuth;
import com.tencent.mm.sdk.openapi.IWXAPI;
import com.tencent.mm.sdk.openapi.IWXAPIEventHandler;
import com.tencent.mm.sdk.openapi.WXAPIFactory;

/**
 * DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY RXPAY. */
public class WXPayEntryActivity extends Activity implements IWXAPIEventHandler {
    private IWXAPI api;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        String appId = WXPayWay.getAppId(this);
        api = WXAPIFactory.createWXAPI(this, appId);
        api.handleIntent(getIntent(), this);;
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
        api.handleIntent(intent, this);;
    }

    @Override
    public void onReq(BaseReq baseReq) {
    }

    @Override
    public void onResp(BaseResp baseResp) {

        ToastUtil.show(this, "111111111:"+baseResp.getClass().getName());


        if(baseResp instanceof SendAuth.Resp){
            SendAuth.Resp newResp = (SendAuth.Resp) baseResp;
            //获取微信传回的code
            String code = newResp.code;
            ToastUtil.show(this, "授权码"+code);
            RxBusManager.getInstance().post(new ThirdOauthEvent(code,0));

        }else
        {



            int errCode = baseResp.errCode;

            if (errCode == 0) {
                ToastUtil.show(this, R.string.state_pay_success);
                RxBusManager.getInstance().post(new PaymentStatus(true));

            }else  if (errCode == -2){
                ToastUtil.show(this, R.string.state_pay_cancle);
                RxBusManager.getInstance().post(new PaymentStatus(false));
            }else
            {
                ToastUtil.show(this, getString(R.string.state_pay_fault)+"---"+errCode);
            }
        }

        finish();
    }
}
